CLASS z2ui5_cl_gui_alv DEFINITION PUBLIC
  FINAL
  CREATE PUBLIC .
  PUBLIC SECTION.
    METHODS display
      IMPORTING
        val TYPE clike.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS z2ui5_cl_gui_alv IMPLEMENTATION.
  METHOD display.



  ENDMETHOD.
ENDCLASS.
